import React, { createContext, useState, useContext } from 'react';

const translations = {
    en: {
        // Landing Page
        heroBadge: "AI-POWERED AGRICULTURE",
        heroTitle: "Transform Your Farm with Intelligent Agriculture",
        heroSubtitle: "Precision insights, automated irrigation, and real-time market access. Transform your harvest with the power of AgroNexus AI.",
        getStarted: "Get Started",
        join: "Join",
        signIn: "Sign In",
        platform: "Platform",
        solutions: "Solutions",
        hardware: "Hardware",
        pricing: "Pricing",
        viewDemo: "View Demo",
        watchDemo: "Watch Demo",
        heroDesc: "Harness AI-powered insights, real-time IoT monitoring, and direct marketplace access to maximize your yield, reduce waste, and increase profitability.",
        waterSavings: "Water Savings",
        aiAccuracy: "AI Accuracy",
        systemIntelligence: "System Intelligence",
        intelTitle: "Built on Proven AgTech Architecture",
        intelSubtitle: "Our platform integrates cutting-edge AI, field-hardened IoT sensors, and real-time analytics to deliver actionable insights directly to your farm.",
        ctaTitle: "Ready to Optimize Your Harvest?",
        ctaSubtitle: "Join thousands of farmers already using AgroNexus to transform their productivity.",
        getStartedFree: "Get Started Free",
        talkToSales: "Talk to Sales",
        footerBrandDesc: "Empowering Cameroonian agriculture through intelligent technology. Built for farmers, for farmers.",
        footerRights: "All rights reserved. Built for Cameroonian Agriculture.",
        company: "Company",
        resources: "Resources",
        features: "Features",
        hardware: "Hardware",
        pricing: "Pricing",
        api: "API",
        about: "About",
        careers: "Careers",
        blog: "Blog",
        contact: "Contact",
        documentation: "Documentation",
        support: "Support",
        community: "Community",
        partners: "Partners",
        testimonialQuote: "AgroNexus changed how I manage my coffee plantation. The AI disease detection saved 30% of my harvest this season.",
        testimonialAuthor: "Jean-Paul Etundi",
        testimonialRole: "Coffee Farmer · West Region",
        yieldIncrease: "Yield Increase",
        fcfaRev: "FCFA Rev",
        toROI: "To ROI",
        aiEngineTitle: "AI Engine",
        aiEngineDesc: "Deep learning models trained on 2M+ crop images detect diseases, pests, and nutrient deficiencies with clinical precision.",
        fieldHardwareTitle: "Field Hardware",
        fieldHardwareDesc: "Military-grade sensors monitor soil, weather, and crop health 24/7.",
        soilSensors: "Soil Sensors",
        weatherStations: "Weather Stations",
        agroMarketTitle: "Agro Marketplace",
        agroMarketDesc: "Connect directly with verified buyers and sellers. Fair pricing, zero middlemen.",
        realTimeIoTTitle: "Real-Time IoT Dashboard",
        realTimeIoTDesc: "High-contrast, sunlight-readable metrics designed for field use. Monitor NPK levels, soil moisture, and more at a glance.",
        soilMoisture: "Soil Moisture",
        npkBalance: "NPK Balance",
        optimal: "Optimal",

        // App Nav
        home: "HOME",
        scanner: "SCANNER",
        marketplace: "MARKETPLACE",
        devices: "DEVICES",
        profile: "PROFILE",

        // Dashboard
        greeting: "Good morning",
        excellentHealth: "Excellent Health",
        farmPerformance: "Your farm is performing 12% above seasonal average.",
        priorityAction: "PRIORITY ACTION",
        dueNow: "DUE NOW",
        irrigateZoneB: "Irrigate Zone B",
        soilMoistureLow: "Soil moisture dropped to 28% (Critical: 35%)",
        waterNow: "WATER NOW",

        // Weather
        weatherToday: "WEATHER TODAY",
        partlyCloudy: "Partly Cloudy",
        high: "High",
        low: "Low",
        nextRain: "Next Rain",
        humidity: "Humidity",
        rainChance: "Rain Chance",
        wind: "Wind",

        // Features
        memberProfile: "MEMBER PROFILE",
        impactData: "Impact Data",
        totalHarvest: "Total Harvest",
        waterSaved: "Water Saved",
        co2Offset: "CO2 Offset",
        achievements: "Achievements",
        hectares: "HECTARES",
        unitHa: "ha",
        unitLitres: "litres",
        unitWeeks: "weeks",
        yieldStreak: "YIELD STREAK",
        healthScore: "HEALTH SCORE",
        systemSettings: "SYSTEM SETTINGS",
        offlineFirst: "OFFLINE FIRST",
        offlineDesc: "Prioritize local data storage",
        languageLabel: "LANGUAGE",
        change: "CHANGE",
        logout: "LOG OUT",
        masterFarmer: "MASTER FARMER",
        language: "English",
        loading: "Loading...",

        // Consumer Profile
        verifiedBuyer: "Verified Buyer",
        memberSince: "Member since",
        walletBalance: "Wallet Balance",
        activityHub: "Activity Hub",
        orderTracking: "Order Tracking",
        currentOrders: "Current Orders",
        purchaseHistory: "Purchase History",
        buyAgain: "Buy Again",
        myReviews: "My Reviews",
        agroEssentials: "Agro-Essentials",
        savedAddresses: "Saved Addresses",
        paymentMethods: "Payment Methods",
        notificationSettings: "Notification Settings",
    },
    fr: {
        // Landing Page
        heroBadge: "AGRICULTURE PROPULSÉE PAR L'IA",
        heroTitle: "Transformez votre Ferme avec l'Agriculture Intelligente",
        heroSubtitle: "Des informations de précision, une irrigation automatisée et un accès au marché en temps réel. Transformez votre récolte avec la puissance de l'IA AgroNexus.",
        getStarted: "Commencer",
        join: "S'inscrire",
        signIn: "Connexion",
        platform: "Plateforme",
        solutions: "Solutions",
        hardware: "Matériel",
        pricing: "Tarification",
        viewDemo: "Voir la Démo",
        watchDemo: "Voir la Démo",
        heroDesc: "Exploitez les informations de l'IA, la surveillance IoT en temps réel et l'accès direct au marché pour maximiser votre rendement et votre rentabilité.",
        waterSavings: "Économies d'Eau",
        aiAccuracy: "Précision de l'IA",
        systemIntelligence: "Intelligence Système",
        intelTitle: "Conçu sur une Architecture AgTech Eprouvée",
        intelSubtitle: "Notre plateforme intègre une IA de pointe, des capteurs IoT éprouvés sur le terrain et des analyses en temps réel pour fournir des informations exploitables directement à votre ferme.",
        ctaTitle: "Prêt à optimiser votre récolte ?",
        ctaSubtitle: "Rejoignez des milliers d'agriculteurs qui utilisent déjà AgroNexus pour transformer leur productivité.",
        getStartedFree: "Commencer Gratuitement",
        talkToSales: "Parler à un Commercial",
        // Additional Keys
        heroTrusted: "Approuvé par des milliers de fermiers au Cameroun",
        intelBadge: "Intelligence Système",
        intelTitle: "Intelligence Agricole",
        intelSubtitle: "Des informations de précision pour votre exploitation.",
        footerBrandDesc: "Renforcer l'agriculture camerounaise grâce à une technologie intelligente. Conçu pour les agriculteurs, par les agriculteurs.",
        footerRights: "Tous droits réservés. Conçu pour l'Agriculture Camerounaise.",
        company: "Entreprise",
        resources: "Ressources",
        features: "Fonctionnalités",
        hardware: "Matériel",
        pricing: "Tarification",
        api: "API",
        about: "À propos",
        careers: "Carrières",
        blog: "Blog",
        contact: "Contact",
        documentation: "Documentation",
        support: "Assistance",
        community: "Communauté",
        partners: "Partenaires",
        testimonialQuote: "AgroNexus a changé ma façon de gérer ma plantation de café. La détection des maladies par l'IA a sauvé 30% de ma récolte cette saison.",
        testimonialAuthor: "Jean-Paul Etundi",
        testimonialRole: "Producteur de Café · Région de l'Ouest",
        yieldIncrease: "Hausse de Rendement",
        fcfaRev: "Revenu FCFA",
        toROI: "Vers ROI",
        aiEngineTitle: "Moteur d'IA",
        aiEngineDesc: "Des modèles d'apprentissage profond entraînés sur plus de 2 millions d'images détectent maladies, ravageurs et carences avec précision.",
        fieldHardwareTitle: "Matériel de Terrain",
        fieldHardwareDesc: "Des capteurs de qualité militaire surveillent le sol, la météo et la santé des cultures 24h/24.",
        soilSensors: "Capteurs de Sol",
        weatherStations: "Stations Météo",
        agroMarketTitle: "Marché Agro",
        agroMarketDesc: "Connectez-vous directement avec des acheteurs et vendeurs vérifiés. Prix équitables, sans intermédiaires.",
        realTimeIoTTitle: "Tableau de Bord IoT",
        realTimeIoTDesc: "Métriques contrastées et lisibles au soleil, conçues pour le terrain. Surveillance NPK, humidité et plus.",
        soilMoisture: "Humidité du Sol",
        npkBalance: "Équilibre NPK",
        optimal: "Optimal",

        // App Nav
        home: "ACCUEIL",
        scanner: "SCANNER",
        marketplace: "MARCHÉ",
        devices: "APPAREILS",
        profile: "PROFIL",

        // Dashboard/Dashboard
        greeting: "Bonjour",
        excellentHealth: "Excellente Santé",
        farmPerformance: "Votre ferme dépasse de 12% la moyenne saisonnière.",
        priorityAction: "ACTION PRIORITAIRE",
        dueNow: "MAINTENANT",
        irrigateZoneB: "Irriguer Zone B",
        soilMoistureLow: "Humidité du sol tombée à 28% (Critique: 35%)",
        waterNow: "ARROSER MAINTENANT",

        // Weather/Météo
        weatherToday: "MÉTÉO AUJOURD'HUI",
        partlyCloudy: "Partiellement Nuageux",
        high: "Max",
        low: "Min",
        nextRain: "Prochaine Pluie",
        humidity: "Humidité",
        rainChance: "Risque de pluie",
        wind: "Vent",

        // Features/Fonctionnalités
        memberProfile: "PROFIL DU MEMBRE",
        impactData: "Données d'impact",
        totalHarvest: "Récolte Totale",
        waterSaved: "Eau Économisée",
        co2Offset: "Compensation CO2",
        achievements: "Réalisations",
        hectares: "HECTARES",
        unitHa: "ha",
        unitLitres: "litres",
        unitWeeks: "semaines",
        yieldStreak: "RECOLTE STREAK",
        healthScore: "SCORE DE SANTÉ",
        systemSettings: "PARAMÈTRES SYSTÈME",
        offlineFirst: "HORS LIGNE D'ABORD",
        offlineDesc: "Prioriser le stockage local",
        languageLabel: "LANGUE",
        change: "CHANGER",
        logout: "DÉCONNEXION",
        masterFarmer: "FERMIER MAÎTRE",
        language: "Français",
        loading: "Chargement...",

        // Consumer Profile
        verifiedBuyer: "Acheteur Vérifié",
        memberSince: "Membre depuis",
        walletBalance: "Solde du Portefeuille",
        activityHub: "Centre d'Activité",
        orderTracking: "Suivi de Commande",
        currentOrders: "Commandes en cours",
        purchaseHistory: "Historique d'Achat",
        buyAgain: "Racheter",
        myReviews: "Mes Avis",
        agroEssentials: "Agro-Essentiels",
        savedAddresses: "Adresses Enregistrées",
        paymentMethods: "Modes de Paiement",
        notificationSettings: "Paramètres de Notification",
    }
};

const LanguageContext = createContext();

export const LanguageProvider = ({ children }) => {
    const [locale, setLocale] = useState('en');

    const t = (key) => {
        return translations[locale][key] || key;
    };

    const toggleLanguage = () => {
        setLocale(prev => (prev === 'en' ? 'fr' : 'en'));
    };

    return (
        <LanguageContext.Provider value={{ locale, t, setLocale, toggleLanguage }}>
            {children}
        </LanguageContext.Provider>
    );
};

export const useLanguage = () => useContext(LanguageContext);
